spring:
  profiles:
    active: ${profile}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size : 200MB
springdoc:
  swagger-ui:
    path: /
    operations-sorter: alpha
    display-request-duration: true