package com.climeet.climeet_backend.domain.retool.gymregistration;

public class EmailTemplates {

    public static final String APPROVE_EMAIL =
        "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\"\n"
            + "    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
            + "<head>\n"
            + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
            + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            + "  <meta name=\"x-apple-disable-message-reformatting\">\n"
            + "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
            + "  <title></title>\n"
            + "  <style type=\"text/css\">\n"
            + "    @media only screen and (min-width: 620px) {\n"
            + "      .u-row {\n"
            + "        width: 600px !important;\n"
            + "      }\n"
            + "\n"
            + "      .u-row .u-col {\n"
            + "        vertical-align: top;\n"
            + "      }\n"
            + "\n"
            + "      .u-row .u-col-100 {\n"
            + "        width: 600px !important;\n"
            + "      }\n"
            + "    }\n"
            + "\n"
            + "    @media (max-width: 620px) {\n"
            + "      .u-row-container {\n"
            + "        max-width: 100% !important;\n"
            + "        padding-left: 0px !important;\n"
            + "        padding-right: 0px !important;\n"
            + "      }\n"
            + "\n"
            + "      .u-row .u-col {\n"
            + "        min-width: 320px !important;\n"
            + "        max-width: 100% !important;\n"
            + "        display: block !important;\n"
            + "      }\n"
            + "\n"
            + "      .u-row {\n"
            + "        width: 100% !important;\n"
            + "      }\n"
            + "\n"
            + "      .u-col {\n"
            + "        width: 100% !important;\n"
            + "      }\n"
            + "\n"
            + "      .u-col > div {\n"
            + "        margin: 0 auto;\n"
            + "      }\n"
            + "    }\n"
            + "\n"
            + "    body {\n"
            + "      margin: 0;\n"
            + "      padding: 0;\n"
            + "    }\n"
            + "\n"
            + "    table,\n"
            + "    tr,\n"
            + "    td {\n"
            + "      vertical-align: top;\n"
            + "      border-collapse: collapse;\n"
            + "    }\n"
            + "\n"
            + "    p {\n"
            + "      margin: 0;\n"
            + "    }\n"
            + "\n"
            + "    .ie-container table,\n"
            + "    .mso-container table {\n"
            + "      table-layout: fixed;\n"
            + "    }\n"
            + "\n"
            + "    * {\n"
            + "      line-height: inherit;\n"
            + "    }\n"
            + "\n"
            + "    a[x-apple-data-detectors='true'] {\n"
            + "      color: inherit !important;\n"
            + "      text-decoration: none !important;\n"
            + "    }\n"
            + "\n"
            + "    table, td {\n"
            + "      color: #000000;\n"
            + "    }\n"
            + "\n"
            + "    #u_body a {\n"
            + "      color: #161a39;\n"
            + "      text-decoration: underline;\n"
            + "    }\n"
            + "  </style>\n"
            + "  <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\"\n"
            + "        type=\"text/css\">\n"
            + "</head>\n"
            + "<body class=\"clean-body u_body\"\n"
            + "      style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #f9f9f9;color: #000000\">\n"
            + "<table id=\"u_body\"\n"
            + "       style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #f9f9f9;width:100%\"\n"
            + "       cellpadding=\"0\" cellspacing=\"0\">\n"
            + "  <tbody>\n"
            + "  <tr style=\"vertical-align: top\">\n"
            + "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
            + "      <div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\">\n"
            + "        <div class=\"u-row\"\n"
            + "             style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
            + "          <div\n"
            + "              style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
            + "            <div class=\"u-col u-col-100\"\n"
            + "                 style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
            + "              <div style=\"height: 100%;width: 100% !important;\">\n"
            + "                <div\n"
            + "                    style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
            + "                  <table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\"\n"
            + "                         cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                    <tbody>\n"
            + "                    <tr>\n"
            + "                      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\"\n"
            + "                          align=\"left\">\n"
            + "                        <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\"\n"
            + "                               cellspacing=\"0\" width=\"100%\"\n"
            + "                               style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f9f9f9;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
            + "                          <tbody>\n"
            + "                          <tr style=\"vertical-align: top\">\n"
            + "                            <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
            + "                              <span>&#160;</span>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                          </tbody>\n"
            + "                        </table>\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                    </tbody>\n"
            + "                  </table>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </div>\n"
            + "      </div>\n"
            + "      <div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "        <div class=\"u-row\"\n"
            + "             style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\n"
            + "          <div\n"
            + "              style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
            + "            <div class=\"u-col u-col-100\"\n"
            + "                 style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
            + "              <div style=\"height: 100%;width: 100% !important;\">\n"
            + "                <div\n"
            + "                    style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
            + "                  <table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\"\n"
            + "                         cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                    <tbody>\n"
            + "                    <tr>\n"
            + "                      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px;font-family:'Lato',sans-serif;\"\n"
            + "                          align=\"left\">\n"
            + "                        <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
            + "                          <tr>\n"
            + "                            <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
            + "                              <img align=\"center\" border=\"0\"\n"
            + "                                   src=\"https://climeet-production-bucket.s3.ap-northeast-2.amazonaws.com/%E1%84%89%E1%85%A5%E1%84%87%E1%85%B5%E1%84%89%E1%85%B3%E1%84%85%E1%85%A9%E1%84%80%E1%85%A9.svg\"\n"
            + "                                   alt=\"Image\" title=\"Image\"\n"
            + "                                   style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 37%;max-width: 214.6px;\"\n"
            + "                                   width=\"214.6\"/>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                        </table>\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                    </tbody>\n"
            + "                  </table>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </div>\n"
            + "      </div>\n"
            + "      <div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "        <div class=\"u-row\"\n"
            + "             style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #161a39;\">\n"
            + "          <div\n"
            + "              style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
            + "            <div class=\"u-col u-col-100\"\n"
            + "                 style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
            + "              <div style=\"background-color: #BEDF22;height: 100%;width: 100% !important;\">\n"
            + "                <div\n"
            + "                    style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
            + "                  <table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\"\n"
            + "                         cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                    <tbody>\n"
            + "                    <tr>\n"
            + "                      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 10px 30px;font-family:'Lato',sans-serif;\"\n"
            + "                          align=\"left\">\n"
            + "                        <div\n"
            + "                            style=\"font-size: 14px; line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
            + "                          <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"> </p>\n"
            + "                          <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span\n"
            + "                              style=\"font-size: 22px; line-height: 30.8px; color: #ffffff; font-family: Lato, sans-serif;\">클밋 승인 안내</span>\n"
            + "                          </p>\n"
            + "                        </div>\n"
            + "\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                    </tbody>\n"
            + "                  </table>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </div>\n"
            + "      </div>\n"
            + "      <div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "        <div class=\"u-row\"\n"
            + "             style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\n"
            + "          <div\n"
            + "              style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
            + "            <div class=\"u-col u-col-100\"\n"
            + "                 style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
            + "              <div style=\"height: 100%;width: 100% !important;\">\n"
            + "                <div\n"
            + "                    style=\"box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
            + "                  <table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\"\n"
            + "                         cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                    <tbody>\n"
            + "                    <tr>\n"
            + "                      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\"\n"
            + "                          align=\"left\">\n"
            + "                        <div\n"
            + "                            style=\"font-size: 14px; line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
            + "                          <p style=\"line-height: 140%;\"><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px;\">안녕하세요. 클밋입니다.</span>\n"
            + "                          </p>\n"
            + "                          <p style=\"line-height: 140%;\"> </p>\n"
            + "                          <p style=\"line-height: 140%;\"><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px;\">회원님의 "
            + "승인~~~ </span><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px;\">임시 "
            + "승인~~되었음을 알려드립니다.</span>\n"
            + "                          </p>\n"
            + "                          <p style=\"line-height: 140%;\"> </p>\n"
            + "                          <p style=\"line-height: 140%;\"><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px;\">승인승인승인~~</span></p>\n"
            + "                          <p style=\"line-height: 140%;\"> </p>\n"
            + "                          <p style=\"line-height: 140%;\"><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px;\">문의사항은 그만!</span>\n"
            + "                          </p>\n"
            + "                          <p style=\"line-height: 140%;\"><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px;\">클밋을 이용해주셔서 감사. </span>\n"
            + "                          </p>\n"
            + "                        </div>\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                    </tbody>\n"
            + "                  </table>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </div>\n"
            + "      </div>\n"
            + "      <div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
            + "        <div class=\"u-row\"\n"
            + "             style=\"margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #18163a;\">\n"
            + "          <div\n"
            + "              style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
            + "            <div class=\"u-col u-col-100\"\n"
            + "                 style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
            + "              <div style=\"background-color: #BEDF22;height: 100%;width: 100% !important;\">\n"
            + "                <div\n"
            + "                    style=\"box-sizing: border-box; height: 100%; padding: 20px 20px 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
            + "                  <table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\"\n"
            + "                         cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                    <tbody>\n"
            + "                    <tr>\n"
            + "                      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\"\n"
            + "                          align=\"left\">\n"
            + "                        <div\n"
            + "                            style=\"font-size: 14px; line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
            + "                          <p style=\"font-size: 14px; line-height: 140%;\"><span\n"
            + "                              style=\"font-size: 16px; line-height: 22.4px; color: #ffffff;\">Contact</span>\n"
            + "                          </p>\n"
            + "                          <p style=\"font-size: 14px; line-height: 140%;\"><span\n"
            + "                              style=\"color: #ffffff; line-height: 19.6px;\"><a rel=\"noopener\"\n"
            + "                                                                              href=\"climeet@gmail.com\"\n"
            + "                                                                              target=\"_blank\"\n"
            + "                                                                              style=\"color: #ffffff;\">climeet@gmail.com</a></span>\n"
            + "                          </p>\n"
            + "                          <p style=\"font-size: 14px; line-height: 140%;\"> </p>\n"
            + "                        </div>\n"
            + "                      </td>\n"
            + "                    </tr>\n"
            + "                    </tbody>\n"
            + "                  </table>\n"
            + "                </div>\n"
            + "              </div>\n"
            + "            </div>\n"
            + "          </div>\n"
            + "        </div>\n"
            + "      </div>\n"
            + "    </td>\n"
            + "  </tr>\n"
            + "  </tbody>\n"
            + "</table>\n"
            + "</body>\n"
            + "\n"
            + "</html>\n";
}